// <auto-generated />
namespace BITCollege_LV.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_NextUniqueNumber_SubClasses : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_NextUniqueNumber_SubClasses));
        
        string IMigrationMetadata.Id
        {
            get { return "202010012130556_added_NextUniqueNumber_SubClasses"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
